export  const  DELETE_LOCATION = 'DELETE_LOCATION';
export  const  ADD_LOCATION_SUCCESS = 'ADD_LOCATION';
export  const  ADD_LOCATION_ERROR = 'ADD_LOCATION_ERROR';
export  const  ADD_LOCATION_REQUEST = 'ADD_LOCATION_REQUEST';



