export  const  DELETE_LOCATION = 'DELETE_LOCATION';
export  const  LOCATION_REQUEST = 'ADD_LOCATION_REQUEST';
export  const  ADD_LOCATION_SUCCESS = 'ADD_LOCATION';
export  const  ADD_LOCATION_ERROR = 'ADD_LOCATION_ERROR';
export  const  EDIT_LOCATION_SUCCESS = 'EDIT_LOCATION_SUCCESS';
export  const  EDIT_LOCATION_ERROR = 'EDIT_LOCATION_ERROR';

